### ISSUE TITLE
XML Parsing Error: CCTOverlaySettings.json not well-formed 

### ISSUE THREAD

**Issue by AftDawn** [viddie/ConsistencyTrackerMod#27]
My `CCTOverlaySettings.json` is the default that is included in the Releases tab.

Here is the error in full:
```
XML Parsing Error: not well-formed
Location: file:///mnt/Linux%20Game%20Drive/Steam/steamapps/common/Celeste/ConsistencyTracker/CCTOverlaySettings.json
Line Number 1, Column 1:
```

It use to work before, i don't know if an update to firefox or this mod is to blame (and yes, i do have `security.fileuri.strict_origin_policy` disabled)

**Comment by viddie** [comment]
This error appearing should not be the root cause of your problem, as it is actually expected.
Here is how it looks for me:
![image](https://user-images.githubusercontent.com/11546103/168022198-ec15638e-0f10-47d3-98c9-ef4857b20d94.png)

I think that error message is due to me making an XML request for a .json/.txt file which are not well-formed XML files, but it still works in getting the content of the file.

Can you explain what issue you are having a little more indepth?

**Comment by AftDawn** [comment]
Oh, wait, this isn't even an issue at all, just found out that all i had set incorrectly was that i didn't turn on the mod

I'm really really sorry

**Comment by viddie** [comment]
No need to be sorry, stuff like that happens lmao.

Have fun with the mod!
